CREATE TABLE AUSLEIHEN_LOG (
    MODIFICATION_USER VARCHAR(10),
    MODIFICATION_DATE DATE,
    ACTION VARCHAR(3),
    MNR_OLD VARCHAR2(4),
    MNR_NEW VARCHAR2(4),
    DVDNR_OLD NUMBER(6),
    DVDNR_NEW NUMBER(6),
    DATUM_OLD DATE,
    DATUM_NEW DATE,
    RUECKGABE_OLD DATE,
    RUECKGABE_NEW DATE
);
